version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3316:3306
  web:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    #pryとかに必要
    tty: true
    stdin_open: true
    volumes:
      - .:/sample_blog_rails7
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/sample_blog_rails7/node_modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysql_data:
  bundle_data:
  node_modules:
